name: 'CodeQL: Init Wrapper'
description: 'Set up CodeQL'
author: 'GitHub'
inputs:
  tools:
    description: URL of CodeQL tools
    required: false
    default: 'https://github.com/kraiouchkine-ghas/init-codeql-customizations/releases/download/codeql-bundle-20221105/codeql-bundle-linux64.tar.gz'
  languages:
    description: The languages to be analysed
    required: false
  token:
    description: GitHub token to use for authenticating with this instance of GitHub. To download custom packs from multiple registries, use the registries input.
    default: ${{ github.token }}
    required: false
  registries:
    description: |
      Use this input only when you need to download CodeQL packages from another instance of GitHub. If you only need to download packages from this GitHub instance, use the token input instead.

      A YAML string that defines the list of GitHub container registries to use for downloading packs. The string is in the following form (the | is required on the first line):

      registries: |
          - url: https://containers.GHEHOSTNAME1/v2/
            packages:
              - my-company/*
              - my-company2/*
            token: \$\{{ secrets.GHEHOSTNAME1_TOKEN }}

          - url: https://ghcr.io/v2/
            packages: */*
            token: \$\{{ secrets.GHCR_TOKEN }}

      The `url` property contains the URL to the container registry you want to connect to.

      The `packages` property contains a single glob string or a list of glob strings, specifying which packages should be retrieved from this particular container registry. Order is important. Earlier entries will match before later entries.

      The `token` property contains a connection token for this registry.    required: false
  matrix:
    default: ${{ toJson(matrix) }}
    required: false
  config-file:
    description: Path of the config file to use
    required: false
    default: ${{ github.workspace }}/codeql/default-codeql-config.yml
  db-location:
    description: Path where CodeQL databases should be created. If not specified, a temporary directory will be used.
    required: false
  config:    
    description: Configuration passed as a YAML string in the same format as the config-file input. This takes precedence over the config-file input.
    required: false
  queries:
    description: Comma-separated list of additional queries to run. By default, this overrides the same setting in a configuration file; prefix with "+" to use both sets of queries.
    required: false
  packs:
    description: >-
      [Experimental] Comma-separated list of packs to run. Reference a pack in the format `scope/name[@version]`. If `version` is not
      specified, then the latest version of the pack is used. By default, this overrides the same setting in a
      configuration file; prefix with "+" to use both sets of packs.

      This input is only available in single-language analyses. To use packs in multi-language
      analyses, you must specify packs in the codeql-config.yml file.
    required: false
  external-repository-token:
    description: A token for fetching external config files and queries if they reside in a private repository in the same GitHub instance that is running this action.
    required: false
  setup-python-dependencies:
    description: Try to auto-install your python dependencies
    required: true
    default: 'true'
  source-root:
    description: Path of the root source code directory, relative to $GITHUB_WORKSPACE.
    required: false
  ram:
    description: >-
      The amount of memory in MB that can be used by CodeQL extractors.
      By default, CodeQL extractors will use most of the memory available in the system
      (which for GitHub-hosted runners is 6GB for Linux, 5.5GB for Windows, and 13GB for macOS).
      This input also sets the amount of memory that can later be used by the "analyze" action.
    required: false
  threads:
    description: >-
      The number of threads that can be used by CodeQL extractors.
      By default, CodeQL extractors will use all the hardware threads available in the system
      (which for GitHub-hosted runners is 2 for Linux and Windows and 3 for macOS).
      This input also sets the number of threads that can later be used by the "analyze" action.
    required: false
  debug:
    description: >-
      Enable debugging mode.
      This will result in more output being produced which may be useful when debugging certain issues.
      Debugging mode is enabled automatically when step debug logging is turned on.
    required: false
    default: 'false'
  debug-artifact-name:
    description: >-
      The name of the artifact to store debugging information in.
      This is only used when debug mode is enabled.
    required: false
  debug-database-name:
    description: >-
      The name of the database uploaded to the debugging artifact.
      This is only used when debug mode is enabled.
    required: false
  trap-caching:
    description: >-
      Explicitly enable or disable TRAP caching rather than respecting the feature flag for it.
    required: false
outputs:
  codeql-path:
    description: The path of the CodeQL binary used for analysis
runs:
  using: "composite"
  steps:
      - id: download-bundle-release
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: |
          gh release download -D ${{ runner.temp }} -R kraiouchkine-ghas/init-codeql-customizations --pattern 'codeql-bundle-linux64.tar.gz'
        shell: bash
      - id: extract-bundle-codeql-config
        run: |
          tar -zxvf ${{ runner.temp }}/codeql-bundle-linux64.tar.gz codeql/default-codeql-config.yml -C ${{ github.workspace }}
        shell: bash
      - id: pre-init
        run: echo pre init
        shell: bash
      - id: set-queries-input-env
        run: |
          queriesinput=$(echo ${{ inputs.queries }})
          [ -z "$queriesinput" ] || [ "${queriesinput:0:1}" = "+" ] || queriesinput_modified="+$queriesinput"; echo "${queriesinput_modified:-$queriesinput}"
          echo "CODEQL_WRAPPER_INPUT_QUERIES=$queriesinput_modified" >> $GITHUB_ENV
        shell: bash
      - id: init
        uses: kraiouchkine-ghas/codeql-action/init@main
        with:
          tools: ${{ inputs.tools }}
          languages: ${{ inputs.languages }}
          token: ${{ inputs.token }}
          registries: ${{ inputs.registries }}
          matrix: ${{ inputs.matrix }}
          config-file: ${{ inputs.config-file }}
          db-location: ${{ inputs.db-location }}
          config: ${{ inputs.config }}
          queries: ${{ env.CODEQL_WRAPPER_INPUT_QUERIES }}
          packs: ${{ inputs.packs }}
          external-repository-token: ${{ inputs.external-repository-token }}
          setup-python-dependencies: ${{ inputs.setup-python-dependencies }}
          source-root: ${{ inputs.source-root }}
          ram: ${{ inputs.ram }}
          threads: ${{ inputs.threads }}
          debug: ${{ inputs.debug }}
          debug-artifact-name: ${{ inputs.debug-artifact-name }}
          debug-database-name: ${{ inputs.debug-database-name }}
          trap-caching: ${{ inputs.trap-caching }}
      - id: post-init
        run: echo post init
        shell: bash
