name: 'CodeQL Wrapper Action Init'
description: 'Initialize and output the CodeQL bundle paths.'
author: 'GitHub'
inputs:
  codeql-action:
    description: 'CodeQL action path.'
    required: true
    default: 'github/codeql-action'
  token:
    description: GitHub token to use for authenticating with this instance of GitHub. To download custom packs from multiple registries, use the registries input.
    default: ${{ github.token }}
    required: false
  tools:
    description: 'CodeQL tools local path, URL, or latest. Note that latest forces the latest release tag unlike the default action.'
    required: true
    default: 'latest'
outputs:
  codeql-tools-path:
    description: 'The local path to the extracted CodeQL tools.'
  codeql-tools-archive-path:
    description: 'The local path to an archived copy of the CodeQL tools.'
runs:
  using: node20
  main: ./dist/index.js
