name: Continuous Integration

on:
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'

jobs:
  test-action:
    name: GitHub Actions Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Test Local Action
        id: test-action
        uses: ./init-codeql-tools
        with:
          codeql-action: 'github/codeql-action'
          tools: 'latest'
          token: ${{ github.token }}

      - name: Print Output
        id: output
        run: echo "${{ steps.test-action.outputs.codeql-tools-path }}"
